// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SD.Tests.Strand7.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AxialBendingFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "AxialBending", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AxialBending.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/AxialBending.feature.ndjson", 17);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 4, DisplayName="Determine the w1 values for beam 1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5.a")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam1()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5.a"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 1", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
 await testRunner.ThenAsync("the w one major should be 1 and w one minor should be 1 for beam 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 10, DisplayName="Determine the w1 values for beam 2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5.a")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam2()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5.a"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 2", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
 await testRunner.ThenAsync("the w one major should be 0.8 and w one minor should be 0.8 for beam 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 16, DisplayName="Determine the w1 values for beam 3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5.a")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam3()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5.a"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 3", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
 await testRunner.ThenAsync("the w one major should be 0.4 and w one minor should be 0.4 for beam 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 22, DisplayName="Determine the w1 values for beam 4")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 4")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5.a")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam4()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5.a"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 4", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
 await testRunner.ThenAsync("the w one major should be 0.6 and w one minor should be 0.6 for beam 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 28, DisplayName="Determine the w1 values for beam 5")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 5")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5.a")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam5()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5.a"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 5", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
 await testRunner.ThenAsync("the w one major should be 0.8 and w one minor should be 0.8 for beam 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 36, DisplayName="Determine the w1 values for beam 6")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 6")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam6()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 6", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
 await testRunner.ThenAsync("the w one major should be 1 and w one minor should be 1 for beam 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 42, DisplayName="Determine the w1 values for beam 8")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 8")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam8()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 8", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
 await testRunner.ThenAsync("the w one major should be 1 and w one minor should be 1 for beam 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 48, DisplayName="Determine the w1 values for beam 10")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 10")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam10()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 10", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
 await testRunner.ThenAsync("the w one major should be 1 and w one minor should be 1 for beam 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 54, DisplayName="Determine the w1 values for beam 12")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 12")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam12()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 12", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
 await testRunner.ThenAsync("the w one major should be 1 and w one minor should be 0.6 for beam 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 60, DisplayName="Determine the w1 values for beam 14")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 14")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam14()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 14", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
 await testRunner.ThenAsync("the w one major should be 1 and w one minor should be 0.8 for beam 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 68, DisplayName="Determine the w1 values for beam 7")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 7")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam7()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 7", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 69
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
 await testRunner.ThenAsync("the w one major should be 0.85 and w one minor should be 0.85 for beam 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 74, DisplayName="Determine the w1 values for beam 9")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 9")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam9()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 9", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
 await testRunner.ThenAsync("the w one major should be 0.85 and w one minor should be 0.85 for beam 9", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 80, DisplayName="Determine the w1 values for beam 11")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 11")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam11()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 11", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 80
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 81
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 82
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
 await testRunner.ThenAsync("the w one major should be 0.85 and w one minor should be 0.4 for beam 11", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 86, DisplayName="Determine the w1 values for beam 13")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 13")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam13()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 13", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
 await testRunner.ThenAsync("the w one major should be 0.6 and w one minor should be 0.85 for beam 13", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 92, DisplayName="Determine the w1 values for beam 15")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the w1 values for beam 15")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("AxialBending")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("13.8.5")]
        public async global::System.Threading.Tasks.Task DetermineTheW1ValuesForBeam15()
        {
            string[] tagsOfScenario = new string[] {
                    "AxialBending",
                    "13.8.5"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the w1 values for beam 15", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
 await testRunner.GivenAsync("the fem test file name is Calculate w1 Values Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 94
 await testRunner.WhenAsync("the uls analysis is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
 await testRunner.ThenAsync("the w one major should be 0.85 and w one minor should be 0.85 for beam 15", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
