// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SD.Tests.Strand7.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ElementLengthFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "ElementLength", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ElementLength.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ElementLength.feature.ndjson", 15);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 4, DisplayName="Determine the effective length 2 of beam 1 in axis 2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 2 of beam 1 in axis 2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam1")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength2OfBeam1InAxis2()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength2",
                    "Axis2",
                    "Beam1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 2 of beam 1 in axis 2", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync("the fem test file name is Element Length Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
 await testRunner.ThenAsync("the L2 chain length of beam 1 should be 14366.6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 10, DisplayName="Determine the effective length 1 of beam 1 in axis 2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 1 of beam 1 in axis 2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam1")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength1OfBeam1InAxis2()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength1",
                    "Axis2",
                    "Beam1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 1 of beam 1 in axis 2", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
 await testRunner.GivenAsync("the fem test file name is Element Length Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
 await testRunner.ThenAsync("the L1 chain length of beam 1 should be 16733.2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 16, DisplayName="Determine the effective length 2 of beam 3 in axis 2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 2 of beam 3 in axis 2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam3")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength2OfBeam3InAxis2()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength2",
                    "Axis2",
                    "Beam3"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 2 of beam 3 in axis 2", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
 await testRunner.GivenAsync("the fem test file name is Element Length Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
 await testRunner.ThenAsync("the L2 chain length of beam 3 should be 3000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 22, DisplayName="Determine the effective length 2 of beam 3 in axis 1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 2 of beam 3 in axis 1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam3")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength2OfBeam3InAxis1()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength2",
                    "Axis1",
                    "Beam3"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 2 of beam 3 in axis 1", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
 await testRunner.GivenAsync("the fem test file name is Element Length Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
 await testRunner.ThenAsync("the L2 chain length of beam 3 should be 6000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 28, DisplayName="Determine the effective length 1 of beam 2 in axis 3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 1 of beam 2 in axis 3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam2")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength1OfBeam2InAxis3()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength1",
                    "Axis3",
                    "Beam2"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 1 of beam 2 in axis 3", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
 await testRunner.GivenAsync("the fem test file name is Element Length Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
 await testRunner.ThenAsync("the L1 chain length of beam 2 should be 9000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 34, DisplayName="Determine the effective length 1 of beam 4 in axis 3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 1 of beam 4 in axis 3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam4")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength1OfBeam4InAxis3()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength1",
                    "Axis3",
                    "Beam4"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 1 of beam 4 in axis 3", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
 await testRunner.GivenAsync("the fem test file name is Element Length Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
 await testRunner.ThenAsync("the L1 chain length of beam 4 should be 9000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 40, DisplayName="Determine the effective length 2 of beam 4 in axis 3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 2 of beam 4 in axis 3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam4")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength2OfBeam4InAxis3()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength2",
                    "Axis3",
                    "Beam4"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 2 of beam 4 in axis 3", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
 await testRunner.GivenAsync("the fem test file name is Element Length Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
 await testRunner.ThenAsync("the L2 chain length of beam 4 should be 14366.6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 46, DisplayName="Determine the effective length 1 of beam 2 in axis 1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 1 of beam 2 in axis 1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam2")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength1OfBeam2InAxis1()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength1",
                    "Axis1",
                    "Beam2"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 1 of beam 2 in axis 1", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
 await testRunner.GivenAsync("the fem test file name is Element Length Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
 await testRunner.ThenAsync("the L1 chain length of beam 2 should be 9000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 52, DisplayName="Determine the effective length 1 of beam 3 in axis 1 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 1 of beam 3 in axis 1 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam3")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength1OfBeam3InAxis1WithBeamRestraints()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength1",
                    "Axis1",
                    "Beam3"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 1 of beam 3 in axis 1 with beam restraints", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
 await testRunner.GivenAsync("the fem test file name is Element Length Restraint Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
 await testRunner.ThenAsync("the L1 chain length of beam 3 should be 1000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 58, DisplayName="Determine the effective length 1 of beam 1 in axis 1 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 1 of beam 1 in axis 1 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam1")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength1OfBeam1InAxis1WithBeamRestraints()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength1",
                    "Axis1",
                    "Beam1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 1 of beam 1 in axis 1 with beam restraints", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
 await testRunner.GivenAsync("the fem test file name is Element Length Restraint Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
 await testRunner.ThenAsync("the L1 chain length of beam 1 should be 2000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 64, DisplayName="Determine the effective length 1 of beam 4 in axis 3 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 1 of beam 4 in axis 3 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam4")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength1OfBeam4InAxis3WithBeamRestraints()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength1",
                    "Axis3",
                    "Beam4"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 1 of beam 4 in axis 3 with beam restraints", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 64
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
 await testRunner.GivenAsync("the fem test file name is Element Length Restraint Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 66
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
 await testRunner.ThenAsync("the L1 chain length of beam 4 should be 2000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 70, DisplayName="Determine the effective length 2 of beam 2 in axis 3 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 2 of beam 2 in axis 3 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis3")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam2")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength2OfBeam2InAxis3WithBeamRestraints()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength2",
                    "Axis3",
                    "Beam2"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 2 of beam 2 in axis 3 with beam restraints", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
 await testRunner.GivenAsync("the fem test file name is Element Length Restraint Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
 await testRunner.ThenAsync("the L2 chain length of beam 2 should be 2000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 76, DisplayName="Determine the effective length 2 of beam 10 in axis 2 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Determine the effective length 2 of beam 10 in axis 2 with beam restraints")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ElementLength")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("EffectiveLength2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Axis2")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Beam10")]
        public async global::System.Threading.Tasks.Task DetermineTheEffectiveLength2OfBeam10InAxis2WithBeamRestraints()
        {
            string[] tagsOfScenario = new string[] {
                    "EffectiveLength2",
                    "Axis2",
                    "Beam10"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Determine the effective length 2 of beam 10 in axis 2 with beam restraints", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 76
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 77
 await testRunner.GivenAsync("the fem test file name is Element Length Restraint Tests.st7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
 await testRunner.WhenAsync("SANS ULS design is run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
 await testRunner.ThenAsync("the L2 chain length of beam 10 should be 2000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
