<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
	  <ReqnrollObsoleteCodeBehindFiles Remove="Features\CompressionOnly - Copy.feature.cs" />
	  <ReqnrollObsoleteCodeBehindFiles Remove="Features\BendingOnly - Copy.feature.cs" />
	  <ReqnrollObsoleteCodeBehindFiles Remove="Features\TensionOnly - Copy.feature.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageReference Include="Reqnroll.Microsoft.Extensions.DependencyInjection" Version="3.3.4" />
		<PackageReference Include="Reqnroll.MSTest" Version="3.3.4" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
		<PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Domain\SD.Element.Design\SD.Element.Design.csproj" />
		<ProjectReference Include="..\..\Domain\SD.Fem.Strand7\SD.Fem.Strand7.csproj" />
		<ProjectReference Include="..\..\SD\SD.csproj" />
		<ProjectReference Include="..\..\UserInterface\SD.UI\SD.UI.csproj" />
		<ProjectReference Include="..\SD.Tests.Shared\SD.Tests.Shared.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Features\Combination.feature.cs">
	    <DependentUpon>Combination.feature</DependentUpon>
	  </Compile>
	  <Compile Update="Features\Compression.feature.cs">
	    <DependentUpon>Compression.feature</DependentUpon>
	  </Compile>
	  <Compile Update="Features\Bending.feature.cs">
	    <DependentUpon>BendingOnly.feature</DependentUpon>
	  </Compile>
	  <Compile Update="Features\Bending.feature.cs">
	    <DependentUpon>Bending.feature</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <None Update="TestFiles\Bending\RHS Bending Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Bending\RHS Bending Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Bending\RHS Bending Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Bending\Column Bending Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Bending\Column Bending Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Combination\RHS Combined Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Combination\RHS Combined Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Combination\RHS Combined Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Combination\Column Combined Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Combination\Column Combined Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Combination\Column Combined Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Compression\RHS Compression Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Compression\RHS Compression Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Compression\RHS Compression Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Compression\Column Compression Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Compression\Column Compression Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Compression\Column Compression Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Compression\Column Bending Test.st7">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Bending\Column Bending Test.st7">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Bending\Column Bending Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Shear\RHS Shear Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Shear\RHS Shear Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Shear\RHS Shear Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Shear\Column Shear Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Shear\Column Shear Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Shear\Column Shear Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Tension\RHS Tension Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Tension\RHS Tension Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Tension\RHS Tension Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Tension\Column Tension Test.LSA">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Tension\Column Tension Test.LSL">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestFiles\Tension\Column Tension Test.st7">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
	<ItemGroup>
	  <ReqnrollFeatureFiles Update="Features\Combination.feature">
	    <Visible>$(UsingMicrosoftNETSdk)</Visible>
	    <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
	  </ReqnrollFeatureFiles>
	  <ReqnrollFeatureFiles Update="Features\Compression.feature">
	    <Visible>$(UsingMicrosoftNETSdk)</Visible>
	    <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
	  </ReqnrollFeatureFiles>
	  <ReqnrollFeatureFiles Update="Features\Bending.feature">
	    <Visible>$(UsingMicrosoftNETSdk)</Visible>
	    <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
	  </ReqnrollFeatureFiles>
	  <ReqnrollFeatureFiles Update="Features\Bending.feature">
	    <Visible>$(UsingMicrosoftNETSdk)</Visible>
	    <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
	  </ReqnrollFeatureFiles>
	</ItemGroup>
</Project>

