// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD.Data;

#nullable disable

namespace SD.Data.Migrations
{
    [DbContext(typeof(StructuralDesignContext))]
    partial class StructuralDesignContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SD.Data.Entities.BeamKValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BeamNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FemFileStableId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("K1")
                        .HasColumnType("REAL");

                    b.Property<double>("K2")
                        .HasColumnType("REAL");

                    b.Property<double>("KeBottom")
                        .HasColumnType("REAL");

                    b.Property<double>("KeTop")
                        .HasColumnType("REAL");

                    b.Property<double>("Kz")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BeamKValues");
                });

            modelBuilder.Entity("SD.Data.Entities.FemFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNameOnly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StableId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FemFiles");
                });

            modelBuilder.Entity("SD.Data.Entities.ModelDesignSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("BeamAllignmentAngleTolerance")
                        .HasColumnType("REAL");

                    b.Property<int>("BeamMinStations")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BeamRestraintAngleTolerance")
                        .HasColumnType("REAL");

                    b.Property<double>("BeamRotationAngleTolerance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelDesignSettings");
                });

            modelBuilder.Entity("SD.Data.Entities.SectionDesignSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FemFileStableId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBottomFlangeRestraint")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBracedFrame")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLateralRestraint")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlateGirder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTopFlangeRestraint")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTorsionalRestraint")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("NetAreaFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("PropertyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WebStiffenerSpacing")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SectionDesignSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
