<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\SD.Core.Infrastructure\SD.Core.Infrastructure.csproj" />
		<ProjectReference Include="..\..\Data\SD.Data\SD.Data.csproj" />
		<ProjectReference Include="..\SD.Element.Design\SD.Element.Design.csproj" />
	</ItemGroup>

</Project>
