<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageReference Include="Reqnroll.Microsoft.Extensions.DependencyInjection" Version="3.3.4" />
		<PackageReference Include="Reqnroll.MSTest" Version="3.3.4" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
		<PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="FemModelView.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="FileBrowserView.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="HeaderView.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="NotificationView.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="SettingsView.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="ToolBarView.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="TestFiles\Beam Resistance Test.LSA">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\Beam Resistance Test.LSL">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\Beam Resistance Test.st7">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\Columns Resistance Tests.LSA">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\Columns Resistance Tests.LSL">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\Columns Resistance Tests.st7">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\Deflection Limit Test.LSA">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\Deflection Limit Test.LSL">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\Deflection Limit Test.st7">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ReqnrollFeatureFiles Update="Features\DeflectionLimit.feature">
			<Visible>$(UsingMicrosoftNETSdk)</Visible>
			<CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
		</ReqnrollFeatureFiles>
		<ReqnrollFeatureFiles Update="Features\CompressionOnly.feature">
			<Visible>$(UsingMicrosoftNETSdk)</Visible>
			<CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
		</ReqnrollFeatureFiles>
		<ReqnrollFeatureFiles Update="Features\BendingOnly.feature">
			<Visible>$(UsingMicrosoftNETSdk)</Visible>
			<CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
		</ReqnrollFeatureFiles>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SD.Tests.Shared\SD.Tests.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="UnitTests\_TestFiles\" />
	</ItemGroup>

</Project>
