<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EPPlus" Version="8.6.3" />
		<PackageReference Include="log4net" Version="3.3.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SD.Core.Shared\SD.Core.Shared.csproj" />
	</ItemGroup>

</Project>
