<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ReqnrollObsoleteCodeBehindFiles Remove="Features\AppliedLoad - Copy.feature.cs" />
    <ReqnrollObsoleteCodeBehindFiles Remove="Features\CompressionOnly.feature.cs" />
    <ReqnrollObsoleteCodeBehindFiles Remove="Features\ElementLength.feature.cs" />
  </ItemGroup>
  <ItemGroup>
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
	  <PackageReference Include="Reqnroll.Microsoft.Extensions.DependencyInjection" Version="3.3.4" />
	  <PackageReference Include="Reqnroll.MSTest" Version="3.3.4" />
	  <PackageReference Include="MSTest.TestAdapter" Version="4.2.1" />
	  <PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SD.Tests.Shared\SD.Tests.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Features\SectionProperties.feature.cs">
      <DependentUpon>SectionProperties.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\AppliedLoad.feature.cs">
      <DependentUpon>AppliedLoad.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\ElementLength.feature.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="TestFiles\Applied loads.LSA">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestFiles\Applied loads.LSL">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestFiles\Applied loads.st7">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestFiles\Columns Resistance Tests.st7">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestFiles\Element Length Restraint Tests.st7">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestFiles\Element Length Tests.st7">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestFiles\Section Properties.st7">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ReqnrollFeatureFiles Update="Features\SectionProperties.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </ReqnrollFeatureFiles>
    <ReqnrollFeatureFiles Update="Features\AppliedLoad.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </ReqnrollFeatureFiles>
    <ReqnrollFeatureFiles Update="Features\ElementLength.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </ReqnrollFeatureFiles>
  </ItemGroup>
</Project>